import { Sofia_Sans } from 'next/font/google'
import './globals.css'

const sofia = Sofia_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Staking Plataform',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sofia.className}>{children}</body>
    </html>
  )
}
